name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: main
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install and deploy
        run: |
          npm install
          npm run build
          sudo supervisorctl stop next
          rm -rf /var/www/plezanjenet/web-next-prev
          mv /var/www/plezanjenet/web-next /var/www/plezanjenet/web-next-prev
          mkdir /var/www/plezanjenet/web-next
          cp -r ./ /var/www/plezanjenet/web-next/
          sudo supervisorctl start next
